### ISSUE TITLE
Search bar and "chercher" button issue

### ISSUE THREAD

**Issue by elodiedaubie** [WildCodeSchool/purple-php-2109-project2-mybooks#21]
When I use "recherche un titre de livre" AND click sur "chercher" (or use enter) : it doens't work. I understand that there are actually two different functionalities there, but it looks like a bug. You should consider separating "Chercher un titre de livre" from all filters so we will understand that we have two different functionalities.

**Comment by Thomas905** [comment]
it's 2 different features but the 2 combine well
