### ISSUE TITLE
css basket

### ISSUE THREAD

**Issue by Carolinecrepin** [WildCodeSchool/purple-php-2109-project2-mybooks#28]
![Capture d’écran du 2021-11-18 15-48-27](https://user-images.githubusercontent.com/90180533/142437993-c2f18c0e-9ecb-416d-8b48-85d52cbc31d7.png)

the small basket I think it is not too much in its place ;)

**Comment by mcbeloy** [comment]
The problem was not reproduced on Firefox or Google Chrome on my machine. Which server did you used?

**Comment by Carolinecrepin** [comment]
I used chrome
